version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=itchatbot

  # Backend API service
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/itchatbot
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend service
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: